apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-auth
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
stringData:
  {{if or .Values.bouncrConsumerUrl .Values.bouncrConsumerUrl .Values.bouncrSubscriptionKey .Values.bouncerResourceId .Values.oauth2KeysUrl}}
  {{- if .Values.bouncrConsumerUrl }}
  aep.security.bouncr.host: "{{ .Values.bouncrConsumerUrl }}"
  {{- end}}
  {{- if .Values.bouncrSubscriptionKey }}
  aep.security.bouncr.subscriptionKey: "{{ .Values.bouncrSubscriptionKey }}"
  {{- end}}
    {{- if .Values.bouncerResourceId }}
  aep.security.bouncr.instanceId: "{{ .Values.bouncerResourceId }}"
  {{- end }}
  {{- if .Values.oauth2KeysUrl }}
  spring.security.oauth2.resourceserver.jwt.jwk-set-uri: "{{ .Values.oauth2KeysUrl }}"
  {{- end }}
  {{- if .Values.service.secret.SPRING_DATASOURCE_PASSWORD }}
  spring.datasource.password: "{{ .Values.service.secret.SPRING_DATASOURCE_PASSWORD }}"
  {{- end }}
  {{else}}{}
  {{end}}
