# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


ingressDomain: "localhost"
moduleInstanceId: "dummy-id"
bouncrConsumerUrl: "dummy"
bouncrSubscriptionKey: "dummy"
bouncerResourceId: "dummy"
oauth2KeysUrl: "dummy"

image:
  repository: devdevdev.azurecr.io/xxx/yyy/zzz-central
  pullPolicy: IfNotPresent
ingress:
  enabled: true
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 500Mi
service:
  secret:
    SPRING_DATASOURCE_PASSWORD: dummy
  database:
    hostname: host.minikube.internal
    port: 5432
    database: xxx
    username: xxx
    password: xxx
env: []


imagePullSecrets: [ ]
